language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip3 install .
  - pip3 install pytest
  - pip3 install coveralls
script:
  - coverage run --source=yamm setup.py test
after_success:
- coveralls
